@database = BigBoxStore
@collection = GroceryInventory
@domain = http://localhost
@port = 3000

###
GET {{domain}}:{{port}}/find/{{database}}/{{collection}}
Content-Type: application/json

###
POST {{domain}}:{{port}}/insert/{{database}}/{{collection}}
Content-Type: application/json

{
  "item": "hamburger",
  "food_group": "proteins",
  "price_in_usd": 10,
  "calories_per_100g": 100
}

###
@put-id=673e61d14ca812dce3d50329
PUT {{domain}}:{{port}}/update/{{database}}/{{collection}}/{{put-id}}
Content-Type: application/json

{
  "item": "ground beef",
  "food_group": "proteins",
  "price_in_usd": 500
}
###
@delete-id = 673e75adab5a708c4424d3c9
DELETE {{domain}}:{{port}}/delete/{{database}}/{{collection}}/{{delete-id}}

### Delete a Collection from a Database
DELETE http://localhost:3000/delete-collection/{{database}}/{{collection}}
Content-Type: application/json

### Insert Many Documents
POST {{domain}}:{{port}}/insert-many/{{database}}/{{collection}}
Content-Type: application/json

[
    {
        "item": "walnuts",
        "food_group": "nuts",
        "price_in_usd": 37,
        "quantity": 100,
        "calories_per_100g": 100
    },
    {
        "item": "red leaf lettuce",
        "food_group": "vegetables",
        "price_in_usd": 1.8,
        "quantity": 70,
        "calories_per_100g": 52,
        "organic": false
    },
    {
        "item": "tuna",
        "food_group": "proteins",
        "price_in_usd": 9.2,
        "quantity": 10,
        "calories_per_100g": 250,
        "wild_caught": true
    }
]